name: Duraprint
favicon: null
layout_spectrum: 0.7196925233583897
typography_spectrum: 0.09074620949104428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3126622827257961
  lightness: 0.15113420668058097
  saturation: 0.8345541327726096
  rhythmicContrast: 0.9591486027929932
purpose: []
